version: "3.4"
services:
  gateway:
    image: nginx:1.15
    depends_on:
      - backend
      - frontend
    volumes:
      - ./docker-scripts/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/frontend
    networks:
      default:
      sparrowdataorg_default:
        aliases:
          - wiscar_sparrow_gateway
  backend:
    build: .
    ports:
      - "50101:5000"
    environment:
      - SPARROW_SECRET_KEY
      - SPARROW_CONFIG_JSON=/cfg/sparrow-config.json
    volumes:
      # Volume for scripts to make things like
      # migrations work...
      # TODO: come up with a better way to organize
      - ./bin:/sparrow-bin
      # Read-only volume for source code
      - ./backend/:/app
      # Nested volume to keep built files
      # separate from those on our local system
      - /app/sparrow.egg-info
      # Share some configuration between backend
      # and frontend
      - cfg:/cfg
  db:
    image: mdillon/postgis:11
    ports:
      - "54325:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=sparrow
    volumes:
      - db_cluster:/var/lib/postgresql/data
      # - ./sparrow-data.pg-dump:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: frontend
    depends_on:
      - backend
    environment:
      - CONTAINERIZED=1
      - SPARROW_CONFIG_JSON=/cfg/sparrow-config.json
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_build:/app/_assets
      - cfg:/cfg
      # Right now, we configure default site content
      # rather than allowing any customization
      - $SPARROW_SITE_CONTENT:/site-content
    expose:
      - 3000
    ports:
      - 30011:3000
volumes:
  frontend_build:
  cfg:
  db_cluster:
networks:
  sparrowdataorg_default:
    external: true
